version: "3"

services:
  beer_service:
    container_name: "beer_service"
    build:
      context: ./beer_service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=foreside_mysql_db
      - DB_PORT=3306
      - DB_NAME=foreside
      - DB_USER=root
      - DB_PASSWORD=123456
    restart: on-failure
    depends_on:
      foreside_mysql_db:
        condition: service_healthy

  gateway:
    container_name: "gateway"
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BEER_SERVICE=beer_service
      - ORDER_SERVICE=order_service
    depends_on:
      - beer_service
      - order_service

  foreside_mysql_db:
    image: mysql:latest
    restart: always
    container_name: "foreside_mysql_db"
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    healthcheck:
      test: [ "CMD-SHELL", 'mysqladmin ping --protocol tcp' ]
      interval: 10s
      timeout: 2s
      retries: 10

  order_service:
    container_name: "order_service"
    build:
      context: ./order_service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - BEER_SERVICE=beer_service
      - BARTENDER_COUNT=4
      - DB_HOST=foreside_mongo_db
      - DB_PORT=27017
      - DB_NAME=foreside

  foreside_mongo_db:
    image: mongo:latest
    restart: always
    container_name: "foreside_mongo_db"
    ports:
      - "27018:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping')"]
      interval: 10s
      timeout: 2s
      retries: 10